<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LocalCoop</AssemblyName>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>../../../mods/LocalCoop/</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LocalCoop.Protocol\LocalCoop.Protocol.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>../../../data_sts2_windows_x86_64/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>../../../data_sts2_windows_x86_64/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
