<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>LocalCoop</AssemblyName>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateDependencyFile>false</GenerateDependencyFile>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <Sts2GameRoot Condition="'$(Sts2GameRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..</Sts2GameRoot>
    <LocalCoopModOutputPath Condition="'$(LocalCoopModOutputPath)' == ''">$(MSBuildThisFileDirectory)..\..\..\mods\LocalCoop\</LocalCoopModOutputPath>
    <OutputPath>$(LocalCoopModOutputPath)</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2GameRoot)\data_sts2_windows_x86_64\0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="sts2">
      <HintPath>$(Sts2GameRoot)\data_sts2_windows_x86_64\sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
