<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\LocalCoop.Broker\LocalCoop.Broker.csproj" />
    <ProjectReference Include="..\LocalCoop.Protocol\LocalCoop.Protocol.csproj" />
  </ItemGroup>
</Project>

